project_id = "cgqwnuhzcehtkcwiords"

[functions.send-staff-approval-email]
verify_jwt = false

[functions.approve-staff]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.auto-reserve-card-members]
verify_jwt = false

[functions.send-fcm-notification]
verify_jwt = false

[functions.onesignal-notification]
verify_jwt = false

[functions.get-onesignal-app-id]
verify_jwt = false

[functions.unified-notification]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false
