project_id = "cgqwnuhzcehtkcwiords"

[functions.send-staff-approval-email]
verify_jwt = false

[functions.approve-staff]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.auto-reserve-card-members]
verify_jwt = false
